print("y0 br0 U t41k l33t?")
i = input()

i = i.replace("A", "4")
i = i.replace("a", "4")
i = i.replace("L", "1")
i = i.replace("l", "1")
i = i.replace("I", "!")
i = i.replace("i", "!")
i = i.replace("H", "#")
i = i.replace("h", "#")
i = i.replace("S", "5")
i = i.replace("s", "5")
i = i.replace("T", "7")
i = i.replace("t", "7")
i = i.replace("O", "0")
i = i.replace("o", "0")
i = i.replace("B", "8")
i = i.replace("b", "8")
i = i.replace("E", "3")
i = i.replace("e", "3")
i = i.replace("Z", "2")
i = i.replace("z", "2")

print("n444#, t#4t'5 n0 h0w u d0 !t m@n:")
print(i)